name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build module
        shell: pwsh
        run: |
          . "$(Build.Repository.LocalPath)/_build/build.ps1"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PowerShell Gallery
        env:
          PS_GALLERY_API_KEY: ${{ secrets.PS_GALLERY_API_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path "$(Build.Repository.LocalPath)/dist" -NuGetApiKey $(PS_GALLERY_API_KEY)
