name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install prerequisites
  #       shell: pwsh
  #       run: |
  #         ./_build/bootstrap.ps1

  #     - name: Run Pester tests
  #       shell: pwsh
  #       run: |
  #         Invoke-Pester -Path "./src"

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    runs-on: ubuntu-latest
    env:
      PS_GALLERY_API_KEY: ${{ secrets.PS_GALLERY_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build module
        shell: pwsh
        run: |
          . ./_build/build.ps1
          
      - name: Deploy to PowerShell Gallery
        shell: pwsh
        run: |
          Publish-Module -Path /dist -NuGetApiKey $env:PS_GALLERY_API_KEY
